[package]
name = "metw-server"
version = "0.1.0"
edition = "2024"

[dependencies]
metw-observability = { path = "../metw-observability" }

tokio = { workspace = true, features = ["net"] }
axum = { workspace = true }
tower-http = { workspace = true, features = ["cors"], optional = true }

[features]
otel = ["metw-observability/otel"]
allow-all-cors = ["dep:tower-http"]

[lints]
workspace = true
